name = "Synixe"
prefix = "synixe"
author = "SynixeBrett"
files = ["mod.cpp", "synixe_logo_transparent_ca.paa", "synixe_x64.dll"]
include = ["./include"]

postbuild = ["!extension"]
releasebuild = ["@zip {{modname}}", "@zip {{key_name}}"]

[scripts.extension]
show_output = true
steps_windows = [
    "cd extension && cargo build --release",
    "copy extension\\target\\release\\synixe.dll synixe_x64.dll"
]
steps_linux = [
    "echo \"Unable to build extension on Linux\""
]
