class NATO {
    class MARPAT_Desert {
        // Becomes: NATO_MARPAT_Desert - Leader
        Leader = QUOTE([["CUP_arifle_M4A1_BUIS_desert_GL","CUP_muzzle_snds_M16","CUP_acc_ANPEQ_2_desert","optic_Hamr",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",4],["ACE_CableTie",2],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACE_microDAGR",1],["ACRE_PRC148",1],["ACRE_PRC343",1],["SmokeShell",1,1],["SmokeShellBlue",1,1],["SmokeShellRed",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",1,30],["1Rnd_HE_Grenade_shell",5,1],["1Rnd_SmokeRed_Grenade_shell",1,1],["ACE_40mm_Flare_green",1,1]]],["CFP_AssaultPack_MarpatDesert",[["ACE_EntrenchingTool",1],["Laserbatteries",1,1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","","ItemCompass","ACE_Altimeter","CUP_NVG_PVS14"]]);
        // Becomes: NATO_MARPAT_Desert - AutoRifleman
        AutoRifleman = QUOTE([["CUP_lmg_m249_pip4","muzzle_snds_m_snd_F","CUP_acc_ANPEQ_2","CUP_optic_ElcanM145",["CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",200],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",1,200],["CUP_100Rnd_TE4_Yellow_Tracer_556x45_M249",1,100],["CUP_30Rnd_556x45_Stanag",1,30]]],["CFP_AssaultPack_MarpatDesert",[["ACE_EntrenchingTool",1],["CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",1,200]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",[],["ItemMap","","","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Medic
        Medic = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_Stanag",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343_ID_1",1],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrier1_khk",[["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",2,30],["SmokeShell",5,1]]],["tacs_Backpack_Kitbag_Medic_Coyote",[["ACE_bodyBag",2],["adv_aceCPR_AED",1],["ACE_bloodIV",11],["ACE_elasticBandage",40],["ACE_morphine",10],["ACE_epinephrine",7],["ACE_tourniquet",5],["ACE_bloodIV_500",2]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Binocular","","","",[],[],""],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ACE_Altimeter","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Ammo_Bearer
        Ammo_Bearer = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1],["CUP_17Rnd_9x19_glock17",1,17]]],["V_PlateCarrier1_khk",[["CUP_30Rnd_556x45_PMAG_QP_Tan",14,30]]],["CFP_Kitbag_MarpatDesert",[["ACE_EntrenchingTool",1],["CUP_30Rnd_556x45_PMAG_QP_Tan",10,30],["CUP_200Rnd_TE4_Yellow_Tracer_556x45_M249",1,200],["Titan_AT",1,1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Marksman
        Marksman = QUOTE([["CUP_srifle_M110","CUP_muzzle_snds_M110","CUP_acc_ANPEQ_15_Flashlight_Tan_L","CUP_optic_Elcan_reflex_Coyote",["CUP_20Rnd_762x51_B_M110",20],[],"CUP_bipod_VLTOR_Modpod"],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","optic_MRD",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrier1_khk",[["ACRE_PRC148",1],["CUP_20Rnd_762x51_B_M110",6,20],["CUP_20Rnd_TE1_Green_Tracer_762x51_M110",3,20]]],["CFP_AssaultPack_MarpatDesert",[["ACE_EntrenchingTool",1],["ACE_Tripod",1]]],"CUP_H_USMC_BOONIE_DES","CUP_PMC_Facewrap_Tan",["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - HAT 
        HAT = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],["launch_O_Titan_short_F","","","",["Titan_AT",1],[],""],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343_ID_1",1],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrier1_khk",[["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",2,30]]],["CFP_AssaultPack_MarpatDesert",[["Titan_AT",1,1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - LAT 
        LAT = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],["CUP_launch_M136","","","",["ACE_PreloadedMissileDummy_CUP",1],[],""],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACRE_PRC343_ID_2",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_30Rnd_556x45_PMAG_QP_Tan",8,30]]],[],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",[],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - JTAC
        JTAC = QUOTE([["NAA_EBR_khaki","muzzle_snds_B_snd_F","CUP_acc_ANPEQ_15","CUP_optic_ACOG_Reflex_Desert",["ACE_20Rnd_762x51_M118LR_Mag",20],[],"CUP_bipod_Harris_1A2_L"],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACRE_PRC343_ID_1",1],["ACRE_PRC148_ID_1",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrier1_khk",[["ACE_20Rnd_762x51_M118LR_Mag",9,20],["CUP_17Rnd_9x19_glock17",2,17],["MiniGrenade",1,1],["SmokeShell",1,1]]],["CFP_Kitbag_MarpatDesert",[["ACE_microDAGR",1],["ACRE_PRC117F_ID_1",1],["Laserbatteries",1,1],["SmokeShellRed",1,1],["SmokeShellBlue",1,1],["SmokeShellOrange",1,1],["MS_Strobe_Mag_1",1,1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","ItemGPS","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Rifleman 
        Rifleman = QUOTE([["CUP_arifle_M16A4_Grip","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15_Flashlight_Black_L","optic_Hamr",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_blk","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",7],["ACE_EarPlugs",1],["ACRE_PRC343_ID_2",1],["ACE_CableTie",2],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",3,30]]],["CFP_AssaultPack_MarpatDesert",[["ACE_EntrenchingTool",1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Binocular","","","",[],[],""],["ItemMap","","","ItemCompass","ACE_Altimeter","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Engineer
        Engineer = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["ACE_VMM3","","","",[],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACE_DefusalKit",1],["ACRE_PRC343_ID_1",1],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrierSpec_cbr",[["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",1,30]]],["CFP_Kitbag_MarpatDesert",[["ACE_EntrenchingTool",1],["ToolKit",1],["ACE_Clacker",1],["SatchelCharge_Remote_Mag",1,1],["DemoCharge_Remote_Mag",3,1],["SLAMDirectionalMine_Wire_Mag",2,1]]],"CUP_H_USMC_MICH2000_COMM_DES","tacs_Goggles_Tan",[],["ItemMap","B_UavTerminal","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - UAV_Operator
        UAV_Operator = QUOTE([["CUP_arifle_M4A3_desert","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15","CUP_optic_MicroT1_coyote",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",5],["ACE_EarPlugs",1],["ACRE_PRC343_ID_2",1],["ACE_tourniquet",2],["ACE_UAVBattery",1],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["V_PlateCarrier1_khk",[["ACRE_PRC148_ID_1",1],["CUP_30Rnd_556x45_PMAG_QP_Tan",7,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",1,30]]],["CFP_Kitbag_MarpatDesert",[["ITC_Land_B_AR2i_Packed",2],["ACE_microDAGR",1],["Laserbatteries",1,1]]],"CUP_H_USMC_MICH2000_COMM_DES","CUP_G_Oakleys_Drk",["Laserdesignator","","","",["Laserbatteries",1],[],""],["ItemMap","B_UavTerminal","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
        // Becomes: NATO_MARPAT_Desert - Grenadier
        Grenadier = QUOTE([["CUP_arifle_M4A1_BUIS_desert_GL","CUP_muzzle_snds_M16_desert","CUP_acc_ANPEQ_15_Flashlight_Black_L","",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACRE_PRC343_ID_1",1],["ACE_tourniquet",2],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_30Rnd_556x45_PMAG_QP_Tan",6,30],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Green",1,30],["1Rnd_HE_Grenade_shell",6,1],["ACE_40mm_Flare_white",2,1],["CUP_1Rnd_Smoke_M203",3,1],["CUP_1Rnd_SmokeRed_M203",1,1]]],["CFP_AssaultPack_MarpatDesert",[["ACE_HuntIR_monitor",1],["ACE_EntrenchingTool",1],["ACE_HuntIR_M203",2,1],["CUP_30Rnd_556x45_PMAG_QP_Tracer_Yellow",1,30],["CUP_1Rnd_StarCluster_White_M203",1,1],["CUP_1Rnd_HEDP_M203",2,1],["CUP_FlareRed_M203",1,1],["CUP_FlareGreen_M203",1,1],["1Rnd_SmokePurple_Grenade_shell",1,1],["1Rnd_SmokeOrange_Grenade_shell",1,1]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",["Binocular","","","",[],[],""],["ItemMap","","ItemRadioAcreFlagged","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])

    };
};

