class Police {
    class Patrol {
		M9 = [[],[],["CUP_hgun_M9","","","",["CUP_15Rnd_9x19_M9",15],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["CUP_15Rnd_9x19_M9",8,15],["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		SOCOM = [[],[],["CUP_hgun_Mk23","","","",["CUP_12Rnd_45ACP_mk23",12],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1],["CUP_12Rnd_45ACP_mk23",8,12]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		Glock = [[],[],["hgun_G17_black_F","","","",["17Rnd_9x21_Mag",17],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1],["16Rnd_9x21_Mag",8,17]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		Walther_P99 = [[],[],["tacs_Walther_P99","","","",["16Rnd_9x21_Mag",17],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1],["16Rnd_9x21_Mag",8,17]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		Grach = [[],[],["hgun_Rook40_F","","","",["16Rnd_9x21_Mag",17],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1],["16Rnd_9x21_Mag",8,17]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		Revolver = [[],[],["CUP_hgun_TaurusTracker455","","","",["CUP_6Rnd_45ACP_M",6],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1]]],["CUP_V_C_Police_Holster",[["ACE_M84",1,1],["SmokeShellBlue",1,1],["ACE_HandFlare_Green",1,1],["ACE_Chemlight_HiBlue",3,1],["ACE_Chemlight_HiRed",1,1],["CUP_6Rnd_45ACP_M",8,6]]],[],"H_Cap_police","G_Aviator",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
		Patrol_CO = [[],[],["hgun_Pistol_heavy_03_F","","","",["6Rnd_127x33_Cylinder",6],[],""],["U_I_P_PoliceOfficer_01_gloves_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_packingBandage",2],["ACE_tourniquet",2],["ACRE_PRC343",1],["6Rnd_127x33_Cylinder",1,6]]],["SP_JackEllis1_PoliceBlack1",[]],["B_Rangmaster_belt_blk",[["ACRE_PRC148",1],["6Rnd_127x33_Cylinder",4,6],["ACE_M84",2,1]]],"SP_PatrolCap_Black","CUP_G_PMC_RadioHeadset_Glasses_Dark",[],["ItemMap","ItemGPS","","ItemCompass","ItemWatch",""]];
	};	
	class SWAT {
		Leader = [["CUP_arifle_G36C_VFG","","CUP_acc_ANPEQ_15_Flashlight_Black_L","CUP_optic_MicroT1",["CUP_30Rnd_TE1_Green_Tracer_556x45_G36",30],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["SP_0000_Standard_PulloverUniform_Black",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1],["ACRE_PRC148",1],["CUP_7Rnd_45ACP_1911",1,7],["CUP_30Rnd_TE1_Green_Tracer_556x45_G36",2,30]]],["SP_JackEllis1_SwatBlack1",[]],["B_Rangmaster_belt_blk",[["CUP_30Rnd_TE1_Green_Tracer_556x45_G36",3,30]]],"CFP_OPS2017_Helmet_Black2","CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset",["Binocular","","","",[],[],""],["ItemMap","ItemGPS","","ItemCompass","ACE_Altimeter",""]];
		Breacher = [["CUP_sgun_M1014","","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","CUP_optic_MicroT1_low",["CUP_8Rnd_B_Beneli_74Slug",8],[],""],[],["ACE_VMH3","","","",[],[],""],["SP_0000_Standard_PulloverUniform_Black",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACRE_PRC343",1],["ACE_DefusalKit",1],["ACE_Clacker",1],["16Rnd_9x21_green_Mag",1,17],["CUP_8Rnd_B_Beneli_74Pellets",3,8]]],["SP_JackEllis1_SwatBlack1",[]],["CUP_B_AssaultPack_Black",[["AMP_Breaching_Charge_Mag",4,1],["DemoCharge_Remote_Mag",2,1],["ACE_M14",2,1],["ACE_M84",4,1],["HandGrenade",2,1]]],"CFP_OPS2017_Helmet_Black2","CUP_G_ESS_RGR_Facewrap_Skull",[],["ItemMap","","","ItemCompass","ItemWatch",""]];
		CLS = [["SMG_03C_TR_black","","CUP_acc_ANPEQ_15_Flashlight_Black_L","CUP_optic_MicroT1_low",["50Rnd_570x28_SMG_03",50],[],""],[],["CUP_hgun_Colt1911","","","",["CUP_7Rnd_45ACP_1911",7],[],""],["SP_0000_Standard_PulloverUniform_Black",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_morphine",2],["ACE_tourniquet",2],["ACRE_PRC343",1],["CUP_7Rnd_45ACP_1911",1,7],["50Rnd_570x28_SMG_03",2,50]]],["SP_JackEllis1_SwatBlack1",[]],["tacs_Backpack_Kitbag_Medic_Black",[["ACE_bloodIV",7],["ACE_elasticBandage",25],["ACE_bloodIV_500",3],["ACE_bodyBag",1],["ACE_epinephrine",5],["ACE_morphine",8],["ACE_tourniquet",5],["ACE_CableTie",2],["50Rnd_570x28_SMG_03",6,50]]],"CFP_OPS2017_Helmet_Black2","G_Respirator_white_F",[],["ItemMap","","","ItemCompass","ItemWatch","Goggles_grn_F"]];
	};
};
